"""add unique constraint on tuner-id x policy generation for checkpoint

Revision ID: abb57b16bc98
Revises: 821cc4f5d981
Create Date: 2026-07-08 13:21:21.875329

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb57b16bc98'
down_revision: Union[str, None] = '821cc4f5d981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_checkpoints_tuner_id_policy_generation', 'checkpoints', ['tuner_id', 'policy_generation'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_checkpoints_tuner_id_policy_generation', 'checkpoints', type_='unique')
    # ### end Alembic commands ###
