"""add_policy_generation_to_in_flight_completion_for_dispense_algorithm

Revision ID: c995075b7dc6
Revises: baf4d96e9d36
Create Date: 2026-07-05 15:43:34.109126

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c995075b7dc6"
down_revision: Union[str, None] = "baf4d96e9d36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_chat_completions_tuner_id_policy_generation",
        "chat_completions",
        ["tuner_id", "policy_generation"],
        unique=False,
    )
    op.add_column(
        "in_flight_chat_completions",
        sa.Column("policy_generation", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("in_flight_chat_completions", "policy_generation")
    op.drop_index(
        "ix_chat_completions_tuner_id_policy_generation", table_name="chat_completions"
    )
    # ### end Alembic commands ###
