"""add hot-path composite indexes to runs

Revision ID: 4cf645b150dc
Revises: 6bfd897f8703
Create Date: 2026-07-02 20:30:08.760954

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4cf645b150dc"
down_revision: Union[str, None] = "6bfd897f8703"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_runs_tuner_id_created_at_id",
        "runs",
        ["tuner_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_runs_tuner_id_trained_count_rejected_count",
        "runs",
        ["tuner_id", "trained_count", "rejected_count"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_runs_tuner_id_trained_count_rejected_count", table_name="runs")
    op.drop_index("ix_runs_tuner_id_created_at_id", table_name="runs")
    # ### end Alembic commands ###
