"""initial schema

Revision ID: 6bfd897f8703
Revises:
Create Date: 2026-07-02 18:21:01.911704

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import ollie_rl.db.models
import ollie_rl.db.types


# revision identifiers, used by Alembic.
revision: str = "6bfd897f8703"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tuners",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("recipe", sa.String(length=255), nullable=False),
        sa.Column("trainer", sa.String(length=255), nullable=False),
        sa.Column("trainer_state", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tuners", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tuners_trainer"), ["trainer"], unique=False
        )

    op.create_table(
        "chat_completions",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("tuner_id", sa.String(length=255), nullable=False),
        sa.Column("policy_generation", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=255), nullable=False),
        sa.Column("datum_id", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=True),
        sa.Column("tokens", ollie_rl.db.models._PackedIntList(), nullable=True),
        sa.Column("logprobs", ollie_rl.db.models._PackedFloatList(), nullable=True),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", ollie_rl.db.types.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", ollie_rl.db.types.UtcDateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["tuner_id"],
            ["tuners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat_completions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chat_completions_datum_id"), ["datum_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_chat_completions_policy_generation"),
            ["policy_generation"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_chat_completions_run_id"), ["run_id"], unique=False
        )
        batch_op.create_index(
            "ix_chat_completions_tuner_id_run_id", ["tuner_id", "run_id"], unique=False
        )
        batch_op.create_index(
            "ix_chat_completions_tuner_id_run_id_request_hash",
            ["tuner_id", "run_id", "request_hash"],
            unique=False,
        )

    op.create_table(
        "datum_rows",
        sa.Column("tuner_id", sa.String(length=255), nullable=False),
        sa.Column("datum_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["tuner_id"],
            ["tuners.id"],
        ),
        sa.PrimaryKeyConstraint("tuner_id", "datum_id"),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("tuner_id", sa.String(length=255), nullable=False),
        sa.Column("datum_id", sa.String(length=255), nullable=False),
        sa.Column("reward", sa.Float(), nullable=True),
        sa.Column("trained_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.Column(
            "expires_at", ollie_rl.db.types.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "created_at", ollie_rl.db.types.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", ollie_rl.db.types.UtcDateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["tuner_id"],
            ["tuners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_runs_datum_id"), ["datum_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_runs_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_runs_tuner_id"), ["tuner_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_tuner_id"))
        batch_op.drop_index(batch_op.f("ix_runs_expires_at"))
        batch_op.drop_index(batch_op.f("ix_runs_datum_id"))

    op.drop_table("runs")
    op.drop_table("datum_rows")
    with op.batch_alter_table("chat_completions", schema=None) as batch_op:
        batch_op.drop_index("ix_chat_completions_tuner_id_run_id_request_hash")
        batch_op.drop_index("ix_chat_completions_tuner_id_run_id")
        batch_op.drop_index(batch_op.f("ix_chat_completions_run_id"))
        batch_op.drop_index(batch_op.f("ix_chat_completions_policy_generation"))
        batch_op.drop_index(batch_op.f("ix_chat_completions_datum_id"))

    op.drop_table("chat_completions")
    with op.batch_alter_table("tuners", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tuners_trainer"))

    op.drop_table("tuners")
    # ### end Alembic commands ###
