"""add in flight chat completion table to record resumable completions

Revision ID: baf4d96e9d36
Revises: 4a89b289ddc9
Create Date: 2026-07-03 21:58:11.791890

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import ollie_rl.db.types

# revision identifiers, used by Alembic.
revision: str = "baf4d96e9d36"
down_revision: Union[str, None] = "4a89b289ddc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "in_flight_chat_completions",
        sa.Column("tuner_id", sa.String(length=255), nullable=False),
        sa.Column("run_id", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=512), nullable=False),
        sa.Column(
            "created_at", ollie_rl.db.types.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", ollie_rl.db.types.UtcDateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["tuner_id"],
            ["tuners.id"],
        ),
        sa.PrimaryKeyConstraint("tuner_id", "run_id", "request_hash"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("in_flight_chat_completions")
    # ### end Alembic commands ###
