"""add duration_ms to record sample duration

Revision ID: 4a89b289ddc9
Revises: 4cf645b150dc
Create Date: 2026-07-03 14:24:01.129510

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a89b289ddc9"
down_revision: Union[str, None] = "4cf645b150dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_completions", sa.Column("duration_ms", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_completions", "duration_ms")
    # ### end Alembic commands ###
