/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tuners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tuners
         * @description Returns a list of all tuners, including id, name, recipe, trainer, and policy_generation.
         */
        get: operations["list_tuners_tuners_get"];
        put?: never;
        /**
         * Create Tuner
         * @description Creates a new LoRA training client / model dynamically from a recipe template.
         */
        post: operations["create_tuner_tuners_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/{tuner_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tuner
         * @description Returns information for a specific tuner, including policy_generation and
         *     stored trainer state. Pass `?progress=true` to also include a recipe-aware
         *     training-progress snapshot (batch readiness, run/group coverage, next pick).
         */
        get: operations["get_tuner_tuners__tuner_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/{tuner_id}/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Data
         * @description Return the full datum-id pool registered for a tuner, so clients can build
         *     a filter dropdown for the runs list.
         */
        get: operations["list_data_tuners__tuner_id__data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/{tuner_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description List runs for a tuner (newest first) with their derived lifecycle status
         *     and recorded chat-completion counts.
         *
         *     Supports cursor-based pagination via `limit`/`cursor`; the response returns
         *     a `next_cursor` when more runs are available. Pass `datum_id` to filter the
         *     listing to runs for a single datum.
         */
        get: operations["list_runs_tuners__tuner_id__runs_get"];
        put?: never;
        /**
         * Dispense Run
         * @description Dispense a run assignment for the tuner.
         *     Returns 200 OK with run_id, datum_id, expires_at.
         *     Or 204 No Content with Retry-After header if no run can be dispensed.
         */
        post: operations["dispense_run_tuners__tuner_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/{tuner_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Return a single run and its chat completions (oldest first) so the full
         *     request/response transcript can be visualized.
         */
        get: operations["get_run_tuners__tuner_id__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/{tuner_id}/runs/{run_id}/completions/{completion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Completion
         * @description Return a single recorded chat completion (request, response, and any
         *     sample-time tensors) so it can be inspected in isolation.
         */
        get: operations["get_completion_tuners__tuner_id__runs__run_id__completions__completion_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openai/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Chat Completion
         * @description Generate a chat completion from the active policy of the requested model.
         *
         *     The tuner/run this completion is attributed to travel in the ``X-Tuner-Id``
         *     / ``X-Run-Id`` headers. See the path-addressed twin
         *     (``/tuners/{tuner_id}/runs/{run_id}/openai/v1/chat/completions``) for a
         *     variant that carries the ids in the URL instead.
         */
        post: operations["create_chat_completion_openai_v1_chat_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/{tuner_id}/runs/{run_id}/openai/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Run Chat Completion
         * @description Path-addressed twin of ``/openai/v1/chat/completions``.
         *
         *     Behaves identically to the header-based endpoint but carries the tuner and
         *     run ids in the URL instead of the ``X-Tuner-Id`` / ``X-Run-Id`` headers.
         *     Encoding the ids in the path keeps them in the request line, which makes
         *     per-run completions easy to search in log aggregators (e.g. Railway).
         */
        post: operations["create_run_chat_completion_tuners__tuner_id__runs__run_id__openai_v1_chat_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/{tuner_id}/runs/{run_id}/reward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Reward
         * @description Sets the reward for a specific run under a tuner.
         */
        put: operations["put_reward_tuners__tuner_id__runs__run_id__reward_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Annotation
         * @description A URL citation when using web search.
         */
        Annotation: {
            /**
             * Type
             * @constant
             */
            type: "url_citation";
            url_citation: components["schemas"]["AnnotationURLCitation"];
        } & {
            [key: string]: unknown;
        };
        /**
         * AnnotationURLCitation
         * @description A URL citation when using web search.
         */
        AnnotationURLCitation: {
            /** End Index */
            end_index: number;
            /** Start Index */
            start_index: number;
            /** Title */
            title: string;
            /** Url */
            url: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Audio
         * @description Data about a previous audio response from the model.
         *     [Learn more](https://platform.openai.com/docs/guides/audio).
         */
        Audio: {
            /** Id */
            id: string;
        };
        /**
         * BatchProgress
         * @description Readiness toward the next train_step.
         */
        BatchProgress: {
            /** Groups Ready */
            groups_ready: number;
            /** Groups In Progress */
            groups_in_progress: number;
        };
        /**
         * ChatCompletion
         * @description Represents a chat completion response returned by model, based on the provided input.
         */
        ChatCompletion: {
            /** Id */
            id: string;
            /** Choices */
            choices: components["schemas"]["Choice"][];
            /** Created */
            created: number;
            /** Model */
            model: string;
            /**
             * Object
             * @constant
             */
            object: "chat.completion";
            moderation?: components["schemas"]["Moderation"] | null;
            /** Service Tier */
            service_tier?: ("auto" | "default" | "flex" | "scale" | "priority") | null;
            /** System Fingerprint */
            system_fingerprint?: string | null;
            usage?: components["schemas"]["CompletionUsage"] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ChatCompletionAssistantMessageParam
         * @description Messages sent by the model in response to user messages.
         */
        "ChatCompletionAssistantMessageParam-Input": {
            /**
             * Role
             * @constant
             */
            role: "assistant";
            audio?: components["schemas"]["Audio"] | null;
            /** Content */
            content?: string | (components["schemas"]["ChatCompletionContentPartTextParam"] | components["schemas"]["ChatCompletionContentPartRefusalParam"])[] | null;
            function_call?: components["schemas"]["FunctionCall-Input"] | null;
            /** Name */
            name?: string;
            /** Refusal */
            refusal?: string | null;
            /** Tool Calls */
            tool_calls?: (components["schemas"]["ChatCompletionMessageFunctionToolCallParam-Input"] | components["schemas"]["ChatCompletionMessageCustomToolCallParam-Input"])[];
        };
        /**
         * ChatCompletionAssistantMessageParam
         * @description Messages sent by the model in response to user messages.
         */
        "ChatCompletionAssistantMessageParam-Output": {
            /**
             * Role
             * @constant
             */
            role: "assistant";
            audio?: components["schemas"]["Audio"] | null;
            /** Content */
            content?: string | (components["schemas"]["ChatCompletionContentPartTextParam"] | components["schemas"]["ChatCompletionContentPartRefusalParam"])[] | null;
            function_call?: components["schemas"]["openai__types__chat__chat_completion_assistant_message_param__FunctionCall"] | null;
            /** Name */
            name?: string;
            /** Refusal */
            refusal?: string | null;
            /** Tool Calls */
            tool_calls?: (components["schemas"]["ChatCompletionMessageFunctionToolCallParam-Output"] | components["schemas"]["ChatCompletionMessageCustomToolCallParam-Output"])[];
        };
        /**
         * ChatCompletionAudio
         * @description If the audio output modality is requested, this object contains data
         *     about the audio response from the model. [Learn more](https://platform.openai.com/docs/guides/audio).
         */
        ChatCompletionAudio: {
            /** Id */
            id: string;
            /** Data */
            data: string;
            /** Expires At */
            expires_at: number;
            /** Transcript */
            transcript: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * ChatCompletionContentPartImageParam
         * @description Learn about [image inputs](https://platform.openai.com/docs/guides/vision).
         */
        ChatCompletionContentPartImageParam: {
            image_url: components["schemas"]["ImageURL"];
            /**
             * Type
             * @constant
             */
            type: "image_url";
        };
        /**
         * ChatCompletionContentPartInputAudioParam
         * @description Learn about [audio inputs](https://platform.openai.com/docs/guides/audio).
         */
        ChatCompletionContentPartInputAudioParam: {
            input_audio: components["schemas"]["InputAudio"];
            /**
             * Type
             * @constant
             */
            type: "input_audio";
        };
        /** ChatCompletionContentPartRefusalParam */
        ChatCompletionContentPartRefusalParam: {
            /** Refusal */
            refusal: string;
            /**
             * Type
             * @constant
             */
            type: "refusal";
        };
        /**
         * ChatCompletionContentPartTextParam
         * @description Learn about [text inputs](https://platform.openai.com/docs/guides/text-generation).
         */
        ChatCompletionContentPartTextParam: {
            /** Text */
            text: string;
            /**
             * Type
             * @constant
             */
            type: "text";
        };
        /**
         * ChatCompletionDetailResponse
         * @description Full detail of a single recorded chat completion for inspection.
         *
         *     Extends the summary fields of `ChatCompletionItem` with the owning
         *     tuner/run/datum identifiers and the optional sample-time tensors
         *     (`tokens`/`logprobs`) so a single completion can be inspected in
         *     isolation.
         */
        ChatCompletionDetailResponse: {
            /** Id */
            id: string;
            /** Tuner Id */
            tuner_id: string;
            /** Run Id */
            run_id: string;
            /** Datum Id */
            datum_id: string;
            /** Policy Generation */
            policy_generation: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms?: number | null;
            request: components["schemas"]["ChatCompletionRequest-Output"];
            response: components["schemas"]["ChatCompletion"];
            /** Tokens */
            tokens?: number[] | null;
            /** Logprobs */
            logprobs?: number[] | null;
        };
        /**
         * ChatCompletionDeveloperMessageParam
         * @description Developer-provided instructions that the model should follow, regardless of
         *     messages sent by the user. With o1 models and newer, `developer` messages
         *     replace the previous `system` messages.
         */
        ChatCompletionDeveloperMessageParam: {
            /** Content */
            content: string | components["schemas"]["ChatCompletionContentPartTextParam"][];
            /**
             * Role
             * @constant
             */
            role: "developer";
            /** Name */
            name?: string;
        };
        /** ChatCompletionFunctionMessageParam */
        ChatCompletionFunctionMessageParam: {
            /** Content */
            content: string | null;
            /** Name */
            name: string;
            /**
             * Role
             * @constant
             */
            role: "function";
        };
        /**
         * ChatCompletionFunctionTool
         * @description A function tool that can be used to generate a response.
         */
        ChatCompletionFunctionTool: {
            function: components["schemas"]["FunctionDefinition"];
            /**
             * Type
             * @constant
             */
            type: "function";
        } & {
            [key: string]: unknown;
        };
        /**
         * ChatCompletionItem
         * @description A single recorded LLM request/response inside a run.
         */
        ChatCompletionItem: {
            /** Id */
            id: string;
            /** Policy Generation */
            policy_generation: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms?: number | null;
            request: components["schemas"]["ChatCompletionRequest-Output"];
            response: components["schemas"]["ChatCompletion"];
        };
        /**
         * ChatCompletionMessage
         * @description A chat completion message generated by the model.
         */
        ChatCompletionMessage: {
            /** Content */
            content?: string | null;
            /** Refusal */
            refusal?: string | null;
            /**
             * Role
             * @constant
             */
            role: "assistant";
            /** Annotations */
            annotations?: components["schemas"]["Annotation"][] | null;
            audio?: components["schemas"]["ChatCompletionAudio"] | null;
            function_call?: components["schemas"]["openai__types__chat__chat_completion_message__FunctionCall"] | null;
            /** Tool Calls */
            tool_calls?: (components["schemas"]["ChatCompletionMessageFunctionToolCall"] | components["schemas"]["ChatCompletionMessageCustomToolCall"])[] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ChatCompletionMessageCustomToolCall
         * @description A call to a custom tool created by the model.
         */
        ChatCompletionMessageCustomToolCall: {
            /** Id */
            id: string;
            custom: components["schemas"]["openai__types__chat__chat_completion_message_custom_tool_call__Custom"];
            /**
             * Type
             * @constant
             */
            type: "custom";
        } & {
            [key: string]: unknown;
        };
        /**
         * ChatCompletionMessageCustomToolCallParam
         * @description A call to a custom tool created by the model.
         */
        "ChatCompletionMessageCustomToolCallParam-Input": {
            /** Id */
            id: string;
            custom: components["schemas"]["Custom-Input"];
            /**
             * Type
             * @constant
             */
            type: "custom";
        };
        /**
         * ChatCompletionMessageCustomToolCallParam
         * @description A call to a custom tool created by the model.
         */
        "ChatCompletionMessageCustomToolCallParam-Output": {
            /** Id */
            id: string;
            custom: components["schemas"]["openai__types__chat__chat_completion_message_custom_tool_call_param__Custom"];
            /**
             * Type
             * @constant
             */
            type: "custom";
        };
        /**
         * ChatCompletionMessageFunctionToolCall
         * @description A call to a function tool created by the model.
         */
        ChatCompletionMessageFunctionToolCall: {
            /** Id */
            id: string;
            function: components["schemas"]["openai__types__chat__chat_completion_message_function_tool_call__Function"];
            /**
             * Type
             * @constant
             */
            type: "function";
        } & {
            [key: string]: unknown;
        };
        /**
         * ChatCompletionMessageFunctionToolCallParam
         * @description A call to a function tool created by the model.
         */
        "ChatCompletionMessageFunctionToolCallParam-Input": {
            /** Id */
            id: string;
            function: components["schemas"]["Function-Input"];
            /**
             * Type
             * @constant
             */
            type: "function";
        };
        /**
         * ChatCompletionMessageFunctionToolCallParam
         * @description A call to a function tool created by the model.
         */
        "ChatCompletionMessageFunctionToolCallParam-Output": {
            /** Id */
            id: string;
            function: components["schemas"]["openai__types__chat__chat_completion_message_function_tool_call_param__Function"];
            /**
             * Type
             * @constant
             */
            type: "function";
        };
        /** ChatCompletionRequest */
        "ChatCompletionRequest-Input": {
            /** Model */
            model: string;
            /** Messages */
            messages: (components["schemas"]["ChatCompletionDeveloperMessageParam"] | components["schemas"]["ChatCompletionSystemMessageParam"] | components["schemas"]["ChatCompletionUserMessageParam"] | components["schemas"]["ChatCompletionAssistantMessageParam-Input"] | components["schemas"]["ChatCompletionToolMessageParam"] | components["schemas"]["ChatCompletionFunctionMessageParam"])[];
            /** Max Tokens */
            max_tokens?: number | null;
            /** Tools */
            tools?: components["schemas"]["ChatCompletionFunctionTool"][] | null;
            /** Stream */
            stream?: boolean | null;
        };
        /** ChatCompletionRequest */
        "ChatCompletionRequest-Output": {
            /** Model */
            model: string;
            /** Messages */
            messages: (components["schemas"]["ChatCompletionDeveloperMessageParam"] | components["schemas"]["ChatCompletionSystemMessageParam"] | components["schemas"]["ChatCompletionUserMessageParam"] | components["schemas"]["ChatCompletionAssistantMessageParam-Output"] | components["schemas"]["ChatCompletionToolMessageParam"] | components["schemas"]["ChatCompletionFunctionMessageParam"])[];
            /** Max Tokens */
            max_tokens?: number | null;
            /** Tools */
            tools?: components["schemas"]["ChatCompletionFunctionTool"][] | null;
            /** Stream */
            stream?: boolean | null;
        };
        /**
         * ChatCompletionSystemMessageParam
         * @description Developer-provided instructions that the model should follow, regardless of
         *     messages sent by the user. With o1 models and newer, use `developer` messages
         *     for this purpose instead.
         */
        ChatCompletionSystemMessageParam: {
            /** Content */
            content: string | components["schemas"]["ChatCompletionContentPartTextParam"][];
            /**
             * Role
             * @constant
             */
            role: "system";
            /** Name */
            name?: string;
        };
        /** ChatCompletionTokenLogprob */
        ChatCompletionTokenLogprob: {
            /** Token */
            token: string;
            /** Bytes */
            bytes?: number[] | null;
            /** Logprob */
            logprob: number;
            /** Top Logprobs */
            top_logprobs: components["schemas"]["TopLogprob"][];
        } & {
            [key: string]: unknown;
        };
        /** ChatCompletionToolMessageParam */
        ChatCompletionToolMessageParam: {
            /** Content */
            content: string | components["schemas"]["ChatCompletionContentPartTextParam"][];
            /**
             * Role
             * @constant
             */
            role: "tool";
            /** Tool Call Id */
            tool_call_id: string;
        };
        /**
         * ChatCompletionUserMessageParam
         * @description Messages sent by an end user, containing prompts or additional context
         *     information.
         */
        ChatCompletionUserMessageParam: {
            /** Content */
            content: string | (components["schemas"]["ChatCompletionContentPartTextParam"] | components["schemas"]["ChatCompletionContentPartImageParam"] | components["schemas"]["ChatCompletionContentPartInputAudioParam"] | components["schemas"]["File"])[];
            /**
             * Role
             * @constant
             */
            role: "user";
            /** Name */
            name?: string;
        };
        /** Choice */
        Choice: {
            /**
             * Finish Reason
             * @enum {string}
             */
            finish_reason: "stop" | "length" | "tool_calls" | "content_filter" | "function_call";
            /** Index */
            index: number;
            logprobs?: components["schemas"]["ChoiceLogprobs"] | null;
            message: components["schemas"]["ChatCompletionMessage"];
        } & {
            [key: string]: unknown;
        };
        /**
         * ChoiceLogprobs
         * @description Log probability information for the choice.
         */
        ChoiceLogprobs: {
            /** Content */
            content?: components["schemas"]["ChatCompletionTokenLogprob"][] | null;
            /** Refusal */
            refusal?: components["schemas"]["ChatCompletionTokenLogprob"][] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * CompletionTokensDetails
         * @description Breakdown of tokens used in a completion.
         */
        CompletionTokensDetails: {
            /** Accepted Prediction Tokens */
            accepted_prediction_tokens?: number | null;
            /** Audio Tokens */
            audio_tokens?: number | null;
            /** Reasoning Tokens */
            reasoning_tokens?: number | null;
            /** Rejected Prediction Tokens */
            rejected_prediction_tokens?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * CompletionUsage
         * @description Usage statistics for the completion request.
         */
        CompletionUsage: {
            /** Completion Tokens */
            completion_tokens: number;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Total Tokens */
            total_tokens: number;
            completion_tokens_details?: components["schemas"]["CompletionTokensDetails"] | null;
            prompt_tokens_details?: components["schemas"]["PromptTokensDetails"] | null;
        } & {
            [key: string]: unknown;
        };
        /** CreateTunerRequest */
        CreateTunerRequest: {
            /** Name */
            name: string;
            /** Recipe */
            recipe: string;
            /** Trainer */
            trainer: string;
            /** Datum Ids */
            datum_ids: string[];
            /** Trainer Params */
            trainer_params?: {
                [key: string]: unknown;
            } | null;
        };
        /** CreateTunerResponse */
        CreateTunerResponse: {
            /** Tuner Id */
            tuner_id: string;
            /** Name */
            name: string;
            /** Recipe */
            recipe: string;
        };
        /**
         * Custom
         * @description The custom tool that the model called.
         */
        "Custom-Input": {
            /** Input */
            input: string;
            /** Name */
            name: string;
        };
        /**
         * DatumCoverage
         * @description How the datum pool is being exercised.
         */
        DatumCoverage: {
            /** In Progress */
            in_progress: number;
            /** Never Trained */
            never_trained: number;
        };
        /**
         * DatumPool
         * @description Datum-pool coverage summary plus per-datum detail.
         */
        DatumPool: {
            coverage: components["schemas"]["DatumCoverage"];
            /** Items */
            items: components["schemas"]["DatumProgress"][];
        };
        /**
         * DatumProgress
         * @description Per-datum group ('Rollout') coverage, trainer view (dynamic).
         */
        DatumProgress: {
            /** Datum Id */
            datum_id: string;
            /** Consumable */
            consumable: number;
            /** In Flight */
            in_flight: number;
            /** Expired */
            expired: number;
            /** Trained */
            trained: number;
            /** Expired Terminal Count */
            expired_terminal_count: number;
            /** Rewarded Terminal Count */
            rewarded_terminal_count: number;
        };
        /** DispenseRun */
        DispenseRun: {
            /** Run Id */
            run_id: string;
            /** Datum Id */
            datum_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * File
         * @description Learn about [file inputs](https://platform.openai.com/docs/guides/text) for text generation.
         */
        File: {
            file: components["schemas"]["FileFile"];
            /**
             * Type
             * @constant
             */
            type: "file";
        };
        /** FileFile */
        FileFile: {
            /** File Data */
            file_data?: string;
            /** File Id */
            file_id?: string;
            /** Filename */
            filename?: string;
        };
        /**
         * Function
         * @description The function that the model called.
         */
        "Function-Input": {
            /** Arguments */
            arguments: string;
            /** Name */
            name: string;
        };
        /**
         * FunctionCall
         * @description Deprecated and replaced by `tool_calls`.
         *
         *     The name and arguments of a function that should be called, as generated by the model.
         */
        "FunctionCall-Input": {
            /** Arguments */
            arguments: string;
            /** Name */
            name: string;
        };
        /** FunctionDefinition */
        FunctionDefinition: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            } | null;
            /** Strict */
            strict?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /** GetTunerResponse */
        GetTunerResponse: {
            /** Tuner Id */
            tuner_id: string;
            /** Name */
            name: string;
            recipe: components["schemas"]["Recipe"];
            /** Trainer */
            trainer: string;
            /** Policy Generation */
            policy_generation: number;
            /** Trainer State */
            trainer_state?: unknown | null;
            progress?: components["schemas"]["TrainingProgress"] | null;
            /**
             * Is Training
             * @default false
             */
            is_training: boolean;
            /** Last Train Op Duration Seconds */
            last_train_op_duration_seconds?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageURL */
        ImageURL: {
            /** Url */
            url: string;
            /**
             * Detail
             * @enum {string}
             */
            detail?: "auto" | "low" | "high";
        };
        /** InputAudio */
        InputAudio: {
            /** Data */
            data: string;
            /**
             * Format
             * @enum {string}
             */
            format: "wav" | "mp3";
        };
        /**
         * ListDatumsResponse
         * @description The full datum-id pool registered for a tuner (for filter dropdowns).
         */
        ListDatumsResponse: {
            /** Datum Ids */
            datum_ids: string[];
        };
        /** ListRunsResponse */
        ListRunsResponse: {
            /** Runs */
            runs: components["schemas"]["RunItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ListTunersResponse */
        ListTunersResponse: {
            /** Tuners */
            tuners: components["schemas"]["TunerItem"][];
        };
        /**
         * Moderation
         * @description Moderation results for the request input and generated output, if moderated
         *     completions were requested.
         */
        Moderation: {
            /** Input */
            input: components["schemas"]["ModerationInputModerationResults"] | components["schemas"]["ModerationInputError"];
            /** Output */
            output: components["schemas"]["ModerationOutputModerationResults"] | components["schemas"]["ModerationOutputError"];
        } & {
            [key: string]: unknown;
        };
        /**
         * ModerationInputError
         * @description An error produced while attempting moderation.
         */
        ModerationInputError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Type
             * @constant
             */
            type: "error";
        } & {
            [key: string]: unknown;
        };
        /**
         * ModerationInputModerationResults
         * @description Successful moderation results for the request input or generated output.
         */
        ModerationInputModerationResults: {
            /** Model */
            model: string;
            /** Results */
            results: components["schemas"]["ModerationInputModerationResultsResult"][];
            /**
             * Type
             * @constant
             */
            type: "moderation_results";
        } & {
            [key: string]: unknown;
        };
        /**
         * ModerationInputModerationResultsResult
         * @description A moderation result produced for the response input or output.
         */
        ModerationInputModerationResultsResult: {
            /** Categories */
            categories: {
                [key: string]: boolean;
            };
            /** Category Applied Input Types */
            category_applied_input_types: {
                [key: string]: ("text" | "image")[];
            };
            /** Category Scores */
            category_scores: {
                [key: string]: number;
            };
            /** Flagged */
            flagged: boolean;
            /** Model */
            model: string;
            /**
             * Type
             * @constant
             */
            type: "moderation_result";
        } & {
            [key: string]: unknown;
        };
        /**
         * ModerationOutputError
         * @description An error produced while attempting moderation.
         */
        ModerationOutputError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Type
             * @constant
             */
            type: "error";
        } & {
            [key: string]: unknown;
        };
        /**
         * ModerationOutputModerationResults
         * @description Successful moderation results for the request input or generated output.
         */
        ModerationOutputModerationResults: {
            /** Model */
            model: string;
            /** Results */
            results: components["schemas"]["ModerationOutputModerationResultsResult"][];
            /**
             * Type
             * @constant
             */
            type: "moderation_results";
        } & {
            [key: string]: unknown;
        };
        /**
         * ModerationOutputModerationResultsResult
         * @description A moderation result produced for the response input or output.
         */
        ModerationOutputModerationResultsResult: {
            /** Categories */
            categories: {
                [key: string]: boolean;
            };
            /** Category Applied Input Types */
            category_applied_input_types: {
                [key: string]: ("text" | "image")[];
            };
            /** Category Scores */
            category_scores: {
                [key: string]: number;
            };
            /** Flagged */
            flagged: boolean;
            /** Model */
            model: string;
            /**
             * Type
             * @constant
             */
            type: "moderation_result";
        } & {
            [key: string]: unknown;
        };
        /**
         * NextPick
         * @description What pick_datum would dispense next, with reasoning (dynamic).
         */
        NextPick: {
            /** Datum Id */
            datum_id: string | null;
            /**
             * Tier
             * @enum {string}
             */
            tier: "incomplete" | "fresh" | "saturated" | "none";
            /** Reason */
            reason: string;
        };
        /**
         * PromptTokensDetails
         * @description Breakdown of tokens used in the prompt.
         */
        PromptTokensDetails: {
            /** Audio Tokens */
            audio_tokens?: number | null;
            /** Cached Tokens */
            cached_tokens?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** PutRewardRequest */
        PutRewardRequest: {
            /** Reward */
            reward: number;
        };
        /** PutRewardResponse */
        PutRewardResponse: {
            /** Run Id */
            run_id: string;
            /** Reward */
            reward: number;
        };
        /**
         * Recipe
         * @description Declarative algorithm-level knobs the TunerService needs to schedule
         *     runs and form training batches. Pure data; knows nothing about backends.
         */
        Recipe: {
            /**
             * Group Size
             * @default 16
             */
            group_size: number;
            /**
             * Num Groups Per Batch
             * @default 32
             */
            num_groups_per_batch: number;
            /**
             * Max Off Policy Generation
             * @default 4
             */
            max_off_policy_generation: number;
            /**
             * Malformed Penalty
             * @default -1
             */
            malformed_penalty: number;
            /**
             * Run Expire Seconds
             * @default 7200
             */
            run_expire_seconds: number;
        };
        /** RunDetailResponse */
        RunDetailResponse: {
            run: components["schemas"]["RunItem"];
            /** Completions */
            completions: components["schemas"]["ChatCompletionItem"][];
        };
        /**
         * RunItem
         * @description Summary of a single run (one attempt at a datum) under a tuner.
         */
        RunItem: {
            /** Run Id */
            run_id: string;
            /** Datum Id */
            datum_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "in_flight" | "expired" | "lost" | "rewarded" | "trained" | "rejected";
            /** Reward */
            reward: number | null;
            /** Policy Generation */
            policy_generation: number | null;
            /** Trained Count */
            trained_count: number;
            /** Rejected Count */
            rejected_count: number;
            /** Completion Count */
            completion_count: number;
            /** Duration Ms Total */
            duration_ms_total?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * RunProgress
         * @description Aggregate run counts across all datums for a tuner (dynamic).
         */
        RunProgress: {
            /** Total */
            total: number;
            /** In Flight */
            in_flight: number;
            /** Expired */
            expired: number;
            /** Lost */
            lost: number;
            /** Rewarded */
            rewarded: number;
            /** Consumable */
            consumable: number;
            /** Trained */
            trained: number;
            /** Rejected */
            rejected: number;
        };
        /** TopLogprob */
        TopLogprob: {
            /** Token */
            token: string;
            /** Bytes */
            bytes?: number[] | null;
            /** Logprob */
            logprob: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * TrainingProgress
         * @description Dynamic snapshot. Thresholds live on the recipe, not here.
         */
        TrainingProgress: {
            batch: components["schemas"]["BatchProgress"];
            runs: components["schemas"]["RunProgress"];
            data: components["schemas"]["DatumPool"];
            next_pick: components["schemas"]["NextPick"];
        };
        /** TunerItem */
        TunerItem: {
            /** Tuner Id */
            tuner_id: string;
            /** Name */
            name: string;
            /** Trainer */
            trainer: string;
            /** Policy Generation */
            policy_generation: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * FunctionCall
         * @description Deprecated and replaced by `tool_calls`.
         *
         *     The name and arguments of a function that should be called, as generated by the model.
         */
        openai__types__chat__chat_completion_assistant_message_param__FunctionCall: {
            /** Arguments */
            arguments: string;
            /** Name */
            name: string;
        };
        /**
         * FunctionCall
         * @description Deprecated and replaced by `tool_calls`.
         *
         *     The name and arguments of a function that should be called, as generated by the model.
         */
        openai__types__chat__chat_completion_message__FunctionCall: {
            /** Arguments */
            arguments: string;
            /** Name */
            name: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Custom
         * @description The custom tool that the model called.
         */
        openai__types__chat__chat_completion_message_custom_tool_call__Custom: {
            /** Input */
            input: string;
            /** Name */
            name: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Custom
         * @description The custom tool that the model called.
         */
        openai__types__chat__chat_completion_message_custom_tool_call_param__Custom: {
            /** Input */
            input: string;
            /** Name */
            name: string;
        };
        /**
         * Function
         * @description The function that the model called.
         */
        openai__types__chat__chat_completion_message_function_tool_call__Function: {
            /** Arguments */
            arguments: string;
            /** Name */
            name: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Function
         * @description The function that the model called.
         */
        openai__types__chat__chat_completion_message_function_tool_call_param__Function: {
            /** Arguments */
            arguments: string;
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_tuners_tuners_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTunersResponse"];
                };
            };
        };
    };
    create_tuner_tuners_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTunerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTunerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tuner_tuners__tuner_id__get: {
        parameters: {
            query?: {
                progress?: boolean;
            };
            header?: never;
            path: {
                tuner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetTunerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_data_tuners__tuner_id__data_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tuner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDatumsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_tuners__tuner_id__runs_get: {
        parameters: {
            query?: {
                /** @description Max runs to return per page. Omit to return every run. */
                limit?: number | null;
                /** @description Opaque forward cursor from a previous response's `next_cursor`. Omit to fetch the first page. */
                cursor?: string | null;
                /** @description Only return runs dispensed for this datum id. */
                datum_id?: string | null;
            };
            header?: never;
            path: {
                tuner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRunsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dispense_run_tuners__tuner_id__runs_post: {
        parameters: {
            query?: {
                /** @description When set, quarantine datums that genuinely keep expiring: a datum is skipped once it has at least half a group's worth of terminal attempts (0.5 * recipe.group_size) and an expiration rate >= this value. Only `expired` runs count -- those that still have a lingering in-flight op (the generation itself stalled past the lease) or whose total duration crossed the expiration threshold; `lost` runs (crashed/abandoned worker, or runs abandoned after their ops completed) are ignored. Omit to disable. */
                max_expire_rate?: number | null;
            };
            header?: never;
            path: {
                tuner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispenseRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_tuners__tuner_id__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tuner_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_completion_tuners__tuner_id__runs__run_id__completions__completion_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tuner_id: string;
                run_id: string;
                completion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatCompletionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_chat_completion_openai_v1_chat_completions_post: {
        parameters: {
            query?: never;
            header: {
                "x-tuner-id": string;
                "x-run-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCompletionRequest-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_chat_completion_tuners__tuner_id__runs__run_id__openai_v1_chat_completions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tuner_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCompletionRequest-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_reward_tuners__tuner_id__runs__run_id__reward_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tuner_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutRewardRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PutRewardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
