/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tuners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tuners
         * @description Returns a list of all tuners, including id, name, recipe, trainer, and policy_generation.
         */
        get: operations["list_tuners_tuners_get"];
        put?: never;
        /**
         * Create Tuner
         * @description Creates a new LoRA training client / model dynamically from a recipe template.
         */
        post: operations["create_tuner_tuners_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/{tuner_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tuner
         * @description Returns information for a specific tuner, including policy_generation and
         *     stored trainer state. Pass `?progress=true` to also include a recipe-aware
         *     training-progress snapshot (batch readiness, run/group coverage, next pick).
         */
        get: operations["get_tuner_tuners__tuner_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openai/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Chat Completion
         * @description Generate a chat completion from the active policy of the requested model.
         *
         *     Real token-by-token streaming is not supported. When ``stream=true`` is
         *     requested, the full completion is generated first and then replayed as a
         *     simulated SSE stream so that OpenAI-compatible clients keep working.
         */
        post: operations["create_chat_completion_openai_v1_chat_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/{tuner_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dispense Run
         * @description Dispense a run assignment for the tuner.
         *     Returns 200 OK with run_id, datum_id, expires_at.
         *     Or 204 No Content with Retry-After header if no run can be dispensed.
         */
        post: operations["dispense_run_tuners__tuner_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/{tuner_id}/runs/{run_id}/reward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Reward
         * @description Sets the reward for a specific run under a tuner.
         */
        put: operations["put_reward_tuners__tuner_id__runs__run_id__reward_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Audio
         * @description Data about a previous audio response from the model.
         *     [Learn more](https://platform.openai.com/docs/guides/audio).
         */
        Audio: {
            /** Id */
            id: string;
        };
        /**
         * BatchProgress
         * @description Readiness toward the next train_step.
         */
        BatchProgress: {
            /** Groups Ready */
            groups_ready: number;
            /** Groups In Progress */
            groups_in_progress: number;
        };
        /**
         * ChatCompletionAssistantMessageParam
         * @description Messages sent by the model in response to user messages.
         */
        ChatCompletionAssistantMessageParam: {
            /**
             * Role
             * @constant
             */
            role: "assistant";
            audio?: components["schemas"]["Audio"] | null;
            /** Content */
            content?: string | (components["schemas"]["ChatCompletionContentPartTextParam"] | components["schemas"]["ChatCompletionContentPartRefusalParam"])[] | null;
            function_call?: components["schemas"]["FunctionCall"] | null;
            /** Name */
            name?: string;
            /** Refusal */
            refusal?: string | null;
            /** Tool Calls */
            tool_calls?: (components["schemas"]["ChatCompletionMessageFunctionToolCallParam"] | components["schemas"]["ChatCompletionMessageCustomToolCallParam"])[];
        };
        /**
         * ChatCompletionContentPartImageParam
         * @description Learn about [image inputs](https://platform.openai.com/docs/guides/vision).
         */
        ChatCompletionContentPartImageParam: {
            image_url: components["schemas"]["ImageURL"];
            /**
             * Type
             * @constant
             */
            type: "image_url";
        };
        /**
         * ChatCompletionContentPartInputAudioParam
         * @description Learn about [audio inputs](https://platform.openai.com/docs/guides/audio).
         */
        ChatCompletionContentPartInputAudioParam: {
            input_audio: components["schemas"]["InputAudio"];
            /**
             * Type
             * @constant
             */
            type: "input_audio";
        };
        /** ChatCompletionContentPartRefusalParam */
        ChatCompletionContentPartRefusalParam: {
            /** Refusal */
            refusal: string;
            /**
             * Type
             * @constant
             */
            type: "refusal";
        };
        /**
         * ChatCompletionContentPartTextParam
         * @description Learn about [text inputs](https://platform.openai.com/docs/guides/text-generation).
         */
        ChatCompletionContentPartTextParam: {
            /** Text */
            text: string;
            /**
             * Type
             * @constant
             */
            type: "text";
        };
        /**
         * ChatCompletionDeveloperMessageParam
         * @description Developer-provided instructions that the model should follow, regardless of
         *     messages sent by the user. With o1 models and newer, `developer` messages
         *     replace the previous `system` messages.
         */
        ChatCompletionDeveloperMessageParam: {
            /** Content */
            content: string | components["schemas"]["ChatCompletionContentPartTextParam"][];
            /**
             * Role
             * @constant
             */
            role: "developer";
            /** Name */
            name?: string;
        };
        /** ChatCompletionFunctionMessageParam */
        ChatCompletionFunctionMessageParam: {
            /** Content */
            content: string | null;
            /** Name */
            name: string;
            /**
             * Role
             * @constant
             */
            role: "function";
        };
        /**
         * ChatCompletionFunctionTool
         * @description A function tool that can be used to generate a response.
         */
        ChatCompletionFunctionTool: {
            function: components["schemas"]["FunctionDefinition"];
            /**
             * Type
             * @constant
             */
            type: "function";
        } & {
            [key: string]: unknown;
        };
        /**
         * ChatCompletionMessageCustomToolCallParam
         * @description A call to a custom tool created by the model.
         */
        ChatCompletionMessageCustomToolCallParam: {
            /** Id */
            id: string;
            custom: components["schemas"]["Custom"];
            /**
             * Type
             * @constant
             */
            type: "custom";
        };
        /**
         * ChatCompletionMessageFunctionToolCallParam
         * @description A call to a function tool created by the model.
         */
        ChatCompletionMessageFunctionToolCallParam: {
            /** Id */
            id: string;
            function: components["schemas"]["Function"];
            /**
             * Type
             * @constant
             */
            type: "function";
        };
        /** ChatCompletionRequest */
        ChatCompletionRequest: {
            /** Model */
            model: string;
            /** Messages */
            messages: (components["schemas"]["ChatCompletionDeveloperMessageParam"] | components["schemas"]["ChatCompletionSystemMessageParam"] | components["schemas"]["ChatCompletionUserMessageParam"] | components["schemas"]["ChatCompletionAssistantMessageParam"] | components["schemas"]["ChatCompletionToolMessageParam"] | components["schemas"]["ChatCompletionFunctionMessageParam"])[];
            /** Max Tokens */
            max_tokens?: number | null;
            /** Tools */
            tools?: components["schemas"]["ChatCompletionFunctionTool"][] | null;
            /** Stream */
            stream?: boolean | null;
        };
        /**
         * ChatCompletionSystemMessageParam
         * @description Developer-provided instructions that the model should follow, regardless of
         *     messages sent by the user. With o1 models and newer, use `developer` messages
         *     for this purpose instead.
         */
        ChatCompletionSystemMessageParam: {
            /** Content */
            content: string | components["schemas"]["ChatCompletionContentPartTextParam"][];
            /**
             * Role
             * @constant
             */
            role: "system";
            /** Name */
            name?: string;
        };
        /** ChatCompletionToolMessageParam */
        ChatCompletionToolMessageParam: {
            /** Content */
            content: string | components["schemas"]["ChatCompletionContentPartTextParam"][];
            /**
             * Role
             * @constant
             */
            role: "tool";
            /** Tool Call Id */
            tool_call_id: string;
        };
        /**
         * ChatCompletionUserMessageParam
         * @description Messages sent by an end user, containing prompts or additional context
         *     information.
         */
        ChatCompletionUserMessageParam: {
            /** Content */
            content: string | (components["schemas"]["ChatCompletionContentPartTextParam"] | components["schemas"]["ChatCompletionContentPartImageParam"] | components["schemas"]["ChatCompletionContentPartInputAudioParam"] | components["schemas"]["File"])[];
            /**
             * Role
             * @constant
             */
            role: "user";
            /** Name */
            name?: string;
        };
        /** CreateTunerRequest */
        CreateTunerRequest: {
            /** Name */
            name: string;
            /** Recipe */
            recipe: string;
            /** Trainer */
            trainer: string;
            /** Datum Ids */
            datum_ids: string[];
            /** Trainer Params */
            trainer_params?: {
                [key: string]: unknown;
            } | null;
        };
        /** CreateTunerResponse */
        CreateTunerResponse: {
            /** Tuner Id */
            tuner_id: string;
            /** Name */
            name: string;
            /** Recipe */
            recipe: string;
        };
        /**
         * Custom
         * @description The custom tool that the model called.
         */
        Custom: {
            /** Input */
            input: string;
            /** Name */
            name: string;
        };
        /**
         * DatumCoverage
         * @description How the datum pool is being exercised.
         */
        DatumCoverage: {
            /** In Progress */
            in_progress: number;
            /** Never Trained */
            never_trained: number;
        };
        /**
         * DatumPool
         * @description Datum-pool coverage summary plus per-datum detail.
         */
        DatumPool: {
            coverage: components["schemas"]["DatumCoverage"];
            /** Items */
            items: components["schemas"]["DatumProgress"][];
        };
        /**
         * DatumProgress
         * @description Per-datum group ('Rollout') coverage, trainer view (dynamic).
         */
        DatumProgress: {
            /** Datum Id */
            datum_id: string;
            /** Consumable */
            consumable: number;
            /** In Flight */
            in_flight: number;
            /** Trained */
            trained: number;
        };
        /** DispenseRun */
        DispenseRun: {
            /** Run Id */
            run_id: string;
            /** Datum Id */
            datum_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * File
         * @description Learn about [file inputs](https://platform.openai.com/docs/guides/text) for text generation.
         */
        File: {
            file: components["schemas"]["FileFile"];
            /**
             * Type
             * @constant
             */
            type: "file";
        };
        /** FileFile */
        FileFile: {
            /** File Data */
            file_data?: string;
            /** File Id */
            file_id?: string;
            /** Filename */
            filename?: string;
        };
        /**
         * Function
         * @description The function that the model called.
         */
        Function: {
            /** Arguments */
            arguments: string;
            /** Name */
            name: string;
        };
        /**
         * FunctionCall
         * @description Deprecated and replaced by `tool_calls`.
         *
         *     The name and arguments of a function that should be called, as generated by the model.
         */
        FunctionCall: {
            /** Arguments */
            arguments: string;
            /** Name */
            name: string;
        };
        /** FunctionDefinition */
        FunctionDefinition: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            } | null;
            /** Strict */
            strict?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /** GetTunerResponse */
        GetTunerResponse: {
            /** Tuner Id */
            tuner_id: string;
            /** Name */
            name: string;
            recipe: components["schemas"]["Recipe"];
            /** Trainer */
            trainer: string;
            /** Policy Generation */
            policy_generation: number;
            /** Trainer State */
            trainer_state?: unknown | null;
            progress?: components["schemas"]["TrainingProgress"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageURL */
        ImageURL: {
            /** Url */
            url: string;
            /**
             * Detail
             * @enum {string}
             */
            detail?: "auto" | "low" | "high";
        };
        /** InputAudio */
        InputAudio: {
            /** Data */
            data: string;
            /**
             * Format
             * @enum {string}
             */
            format: "wav" | "mp3";
        };
        /** ListTunersResponse */
        ListTunersResponse: {
            /** Tuners */
            tuners: components["schemas"]["TunerItem"][];
        };
        /**
         * NextPick
         * @description What _pick_datum would dispense next, with reasoning (dynamic).
         */
        NextPick: {
            /** Datum Id */
            datum_id: string | null;
            /**
             * Tier
             * @enum {string}
             */
            tier: "incomplete" | "fresh" | "saturated" | "none";
            /** Reason */
            reason: string;
        };
        /** PutRewardRequest */
        PutRewardRequest: {
            /** Reward */
            reward: number;
        };
        /** PutRewardResponse */
        PutRewardResponse: {
            /** Run Id */
            run_id: string;
            /** Reward */
            reward: number;
        };
        /**
         * Recipe
         * @description Declarative algorithm-level knobs the TunerService needs to schedule
         *     runs and form training batches. Pure data; knows nothing about backends.
         */
        Recipe: {
            /**
             * Group Size
             * @default 16
             */
            group_size: number;
            /**
             * Num Groups Per Batch
             * @default 32
             */
            num_groups_per_batch: number;
            /**
             * Max Off Policy Generation
             * @default 4
             */
            max_off_policy_generation: number;
            /**
             * Malformed Penalty
             * @default -1
             */
            malformed_penalty: number;
        };
        /**
         * RunProgress
         * @description Aggregate run counts across all datums for a tuner (dynamic).
         */
        RunProgress: {
            /** Total */
            total: number;
            /** In Flight */
            in_flight: number;
            /** Expired */
            expired: number;
            /** Rewarded */
            rewarded: number;
            /** Consumable */
            consumable: number;
            /** Trained */
            trained: number;
            /** Rejected */
            rejected: number;
        };
        /**
         * TrainingProgress
         * @description Dynamic snapshot. Thresholds live on the recipe, not here.
         */
        TrainingProgress: {
            batch: components["schemas"]["BatchProgress"];
            runs: components["schemas"]["RunProgress"];
            data: components["schemas"]["DatumPool"];
            next_pick: components["schemas"]["NextPick"];
        };
        /** TunerItem */
        TunerItem: {
            /** Tuner Id */
            tuner_id: string;
            /** Name */
            name: string;
            /** Trainer */
            trainer: string;
            /** Policy Generation */
            policy_generation: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_tuners_tuners_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTunersResponse"];
                };
            };
        };
    };
    create_tuner_tuners_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTunerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTunerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tuner_tuners__tuner_id__get: {
        parameters: {
            query?: {
                progress?: boolean;
            };
            header?: never;
            path: {
                tuner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetTunerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_chat_completion_openai_v1_chat_completions_post: {
        parameters: {
            query?: never;
            header: {
                "x-tuner-id": string;
                "x-run-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCompletionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dispense_run_tuners__tuner_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tuner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispenseRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_reward_tuners__tuner_id__runs__run_id__reward_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tuner_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutRewardRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PutRewardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
