/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tuners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tuners
         * @description Returns a list of all tuners, including id, name, recipe, trainer, and policy_generation.
         */
        get: operations["list_tuners_tuners_get"];
        put?: never;
        /**
         * Initialize a new training job
         * @description Create and initialize a training job.
         *
         *     Registers the training and optional evaluation datum ids, selects the
         *     recipe and trainer backend, and returns the tuner id used by every
         *     subsequent run, completion, and reward request.
         */
        post: operations["create_tuner_tuners_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/{tuner_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tuner
         * @description Returns information for a specific tuner, including policy_generation and
         *     stored trainer state. Pass `?progress=train` and/or `?progress=eval`
         *     (comma-separated) to also include the corresponding progress snapshot(s)
         *     under the response's `progress` object.
         */
        get: operations["get_tuner_tuners__tuner_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/{tuner_id}/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Data
         * @description Return the datum-id pool registered for a tuner, so clients can build a
         *     filter dropdown for the runs list. Pass `split=train`/`eval` to scope the
         *     pool to a single split.
         */
        get: operations["list_data_tuners__tuner_id__data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/{tuner_id}/reward-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reward Distribution
         * @description Reward distribution bucketed by policy generation for a tuner.
         *
         *     Reads only `(reward, generation)` per rewarded run and returns the finished
         *     per-generation histogram, so the dashboard doesn't fetch every run to
         *     aggregate client-side. Pass `datum_id` to scope to a single datum, and
         *     `kind=eval` to bucket the held-out eval split by checkpoint generation.
         */
        get: operations["reward_distribution_tuners__tuner_id__reward_distribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/{tuner_id}/in-flight-chat-completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List In Flight Chat Completions
         * @description List durable resumable chat-completion operations tracked for a tuner.
         */
        get: operations["list_in_flight_chat_completions_tuners__tuner_id__in_flight_chat_completions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/{tuner_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description List runs for a tuner (newest first) with their derived lifecycle status
         *     and recorded chat-completion counts.
         *
         *     Supports cursor-based pagination via `limit`/`cursor`; the response returns
         *     a `next_cursor` when more runs are available. Pass `datum_id` to filter the
         *     listing to runs for a single datum, and `kind` to restrict to training vs
         *     held-out eval runs.
         */
        get: operations["list_runs_tuners__tuner_id__runs_get"];
        put?: never;
        /**
         * Lease the next run assignment
         * @description Lease the next training assignment to a worker.
         *
         *     A successful response contains the ``run_id``, assigned ``datum_id``, and
         *     ``expires_at``. The initial lease lasts 15 minutes. While a run's chat
         *     completion HTTP request is active, the server heartbeats its deadline; when
         *     that request ends, successfully or otherwise, a fresh 15-minute window
         *     begins. A run therefore expires only after it has had no in-flight
         *     completion request for 15 minutes, at which point its datum may be assigned
         *     under a new run id and the expired run no longer accepts completions or a
         *     reward.
         *
         *     Returns ``204 No Content`` with ``Retry-After: 1`` when work is temporarily
         *     unavailable, such as during trainer warm-up or a training barrier.
         */
        post: operations["dispense_run_tuners__tuner_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/{tuner_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Return a single run and its chat completions (oldest first) so the full
         *     request/response transcript can be visualized.
         */
        get: operations["get_run_tuners__tuner_id__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/{tuner_id}/runs/{run_id}/completions/{completion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Completion
         * @description Return a single recorded chat completion (request, response, and any
         *     sample-time tensors) so it can be inspected in isolation.
         */
        get: operations["get_completion_tuners__tuner_id__runs__run_id__completions__completion_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/{tuner_id}/runs/{run_id}/openai/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sample the active policy for a run
         * @description Generate and record an OpenAI-compatible completion for a training run.
         *
         *     The tuner and run ids are encoded in the URL, making each request directly
         *     attributable and easy to trace in logs. The run must be active and
         *     unrewarded. ``stream=true`` is supported through a simulated SSE stream.
         */
        post: operations["create_run_chat_completion_tuners__tuner_id__runs__run_id__openai_v1_chat_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners/{tuner_id}/runs/{run_id}/reward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Submit a run's final reward
         * @description Submit the final scalar reward for a completed run.
         *
         *     Rewards are write-once and must be submitted before the run lease expires.
         *     The run must contain at least one recorded completion. Accepted rewards are
         *     collected by the server's background training loop; clients do not trigger
         *     a training step separately.
         */
        put: operations["put_reward_tuners__tuner_id__runs__run_id__reward_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Annotation
         * @description A URL citation when using web search.
         */
        Annotation: {
            /**
             * Type
             * @constant
             */
            type: "url_citation";
            url_citation: components["schemas"]["AnnotationURLCitation"];
        } & {
            [key: string]: unknown;
        };
        /**
         * AnnotationURLCitation
         * @description A URL citation when using web search.
         */
        AnnotationURLCitation: {
            /** End Index */
            end_index: number;
            /** Start Index */
            start_index: number;
            /** Title */
            title: string;
            /** Url */
            url: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Audio
         * @description Data about a previous audio response from the model.
         *     [Learn more](https://platform.openai.com/docs/guides/audio).
         */
        Audio: {
            /** Id */
            id: string;
        };
        /**
         * BatchProgress
         * @description Readiness of the strict corpus-ordered groups for the next train_step.
         */
        BatchProgress: {
            /** Groups Ready */
            groups_ready: number;
            /** Groups In Progress */
            groups_in_progress: number;
        };
        /**
         * ChatCompletion
         * @description Represents a chat completion response returned by model, based on the provided input.
         */
        ChatCompletion: {
            /** Id */
            id: string;
            /** Choices */
            choices: components["schemas"]["Choice"][];
            /** Created */
            created: number;
            /** Model */
            model: string;
            /**
             * Object
             * @constant
             */
            object: "chat.completion";
            moderation?: components["schemas"]["Moderation"] | null;
            /** Service Tier */
            service_tier?: ("auto" | "default" | "flex" | "scale" | "priority") | null;
            /** System Fingerprint */
            system_fingerprint?: string | null;
            usage?: components["schemas"]["CompletionUsage"] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ChatCompletionAssistantMessageParam
         * @description Messages sent by the model in response to user messages.
         */
        "ChatCompletionAssistantMessageParam-Input": {
            /**
             * Role
             * @constant
             */
            role: "assistant";
            audio?: components["schemas"]["Audio"] | null;
            /** Content */
            content?: string | (components["schemas"]["ChatCompletionContentPartTextParam"] | components["schemas"]["ChatCompletionContentPartRefusalParam"])[] | null;
            function_call?: components["schemas"]["FunctionCall-Input"] | null;
            /** Name */
            name?: string;
            /** Refusal */
            refusal?: string | null;
            /** Tool Calls */
            tool_calls?: (components["schemas"]["ChatCompletionMessageFunctionToolCallParam-Input"] | components["schemas"]["ChatCompletionMessageCustomToolCallParam-Input"])[];
        };
        /**
         * ChatCompletionAssistantMessageParam
         * @description Messages sent by the model in response to user messages.
         */
        "ChatCompletionAssistantMessageParam-Output": {
            /**
             * Role
             * @constant
             */
            role: "assistant";
            audio?: components["schemas"]["Audio"] | null;
            /** Content */
            content?: string | (components["schemas"]["ChatCompletionContentPartTextParam"] | components["schemas"]["ChatCompletionContentPartRefusalParam"])[] | null;
            function_call?: components["schemas"]["openai__types__chat__chat_completion_assistant_message_param__FunctionCall"] | null;
            /** Name */
            name?: string;
            /** Refusal */
            refusal?: string | null;
            /** Tool Calls */
            tool_calls?: (components["schemas"]["ChatCompletionMessageFunctionToolCallParam-Output"] | components["schemas"]["ChatCompletionMessageCustomToolCallParam-Output"])[];
        };
        /**
         * ChatCompletionAudio
         * @description If the audio output modality is requested, this object contains data
         *     about the audio response from the model. [Learn more](https://platform.openai.com/docs/guides/audio).
         */
        ChatCompletionAudio: {
            /** Id */
            id: string;
            /** Data */
            data: string;
            /** Expires At */
            expires_at: number;
            /** Transcript */
            transcript: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * ChatCompletionContentPartImageParam
         * @description Learn about [image inputs](https://platform.openai.com/docs/guides/vision).
         */
        ChatCompletionContentPartImageParam: {
            image_url: components["schemas"]["ImageURL"];
            /**
             * Type
             * @constant
             */
            type: "image_url";
        };
        /**
         * ChatCompletionContentPartInputAudioParam
         * @description Learn about [audio inputs](https://platform.openai.com/docs/guides/audio).
         */
        ChatCompletionContentPartInputAudioParam: {
            input_audio: components["schemas"]["InputAudio"];
            /**
             * Type
             * @constant
             */
            type: "input_audio";
        };
        /** ChatCompletionContentPartRefusalParam */
        ChatCompletionContentPartRefusalParam: {
            /** Refusal */
            refusal: string;
            /**
             * Type
             * @constant
             */
            type: "refusal";
        };
        /**
         * ChatCompletionContentPartTextParam
         * @description Learn about [text inputs](https://platform.openai.com/docs/guides/text-generation).
         */
        ChatCompletionContentPartTextParam: {
            /** Text */
            text: string;
            /**
             * Type
             * @constant
             */
            type: "text";
        };
        /**
         * ChatCompletionDetailResponse
         * @description Full detail of a single recorded chat completion for inspection.
         *
         *     Extends the summary fields of `ChatCompletionItem` with the owning
         *     tuner/run/datum identifiers and the optional sample-time tensors
         *     (`tokens`/`logprobs`) so a single completion can be inspected in
         *     isolation.
         */
        ChatCompletionDetailResponse: {
            /** Id */
            id: string;
            /** Tuner Id */
            tuner_id: string;
            /** Run Id */
            run_id: string;
            /** Datum Id */
            datum_id: string;
            /** Policy Generation */
            policy_generation: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms?: number | null;
            request: components["schemas"]["ChatCompletionRequest-Output"];
            response: components["schemas"]["ChatCompletion"];
            /** Tokens */
            tokens?: number[] | null;
            /** Logprobs */
            logprobs?: number[] | null;
        };
        /**
         * ChatCompletionDeveloperMessageParam
         * @description Developer-provided instructions that the model should follow, regardless of
         *     messages sent by the user. With o1 models and newer, `developer` messages
         *     replace the previous `system` messages.
         */
        ChatCompletionDeveloperMessageParam: {
            /** Content */
            content: string | components["schemas"]["ChatCompletionContentPartTextParam"][];
            /**
             * Role
             * @constant
             */
            role: "developer";
            /** Name */
            name?: string;
        };
        /** ChatCompletionFunctionMessageParam */
        ChatCompletionFunctionMessageParam: {
            /** Content */
            content: string | null;
            /** Name */
            name: string;
            /**
             * Role
             * @constant
             */
            role: "function";
        };
        /**
         * ChatCompletionFunctionTool
         * @description A function tool that can be used to generate a response.
         */
        ChatCompletionFunctionTool: {
            function: components["schemas"]["FunctionDefinition"];
            /**
             * Type
             * @constant
             */
            type: "function";
        } & {
            [key: string]: unknown;
        };
        /**
         * ChatCompletionItem
         * @description A single recorded LLM request/response inside a run.
         */
        ChatCompletionItem: {
            /** Id */
            id: string;
            /** Policy Generation */
            policy_generation: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms?: number | null;
            request: components["schemas"]["ChatCompletionRequest-Output"];
            response: components["schemas"]["ChatCompletion"];
        };
        /**
         * ChatCompletionMessage
         * @description A chat completion message generated by the model.
         */
        ChatCompletionMessage: {
            /** Content */
            content?: string | null;
            /** Refusal */
            refusal?: string | null;
            /**
             * Role
             * @constant
             */
            role: "assistant";
            /** Annotations */
            annotations?: components["schemas"]["Annotation"][] | null;
            audio?: components["schemas"]["ChatCompletionAudio"] | null;
            function_call?: components["schemas"]["openai__types__chat__chat_completion_message__FunctionCall"] | null;
            /** Tool Calls */
            tool_calls?: (components["schemas"]["ChatCompletionMessageFunctionToolCall"] | components["schemas"]["ChatCompletionMessageCustomToolCall"])[] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ChatCompletionMessageCustomToolCall
         * @description A call to a custom tool created by the model.
         */
        ChatCompletionMessageCustomToolCall: {
            /** Id */
            id: string;
            custom: components["schemas"]["openai__types__chat__chat_completion_message_custom_tool_call__Custom"];
            /**
             * Type
             * @constant
             */
            type: "custom";
        } & {
            [key: string]: unknown;
        };
        /**
         * ChatCompletionMessageCustomToolCallParam
         * @description A call to a custom tool created by the model.
         */
        "ChatCompletionMessageCustomToolCallParam-Input": {
            /** Id */
            id: string;
            custom: components["schemas"]["Custom-Input"];
            /**
             * Type
             * @constant
             */
            type: "custom";
        };
        /**
         * ChatCompletionMessageCustomToolCallParam
         * @description A call to a custom tool created by the model.
         */
        "ChatCompletionMessageCustomToolCallParam-Output": {
            /** Id */
            id: string;
            custom: components["schemas"]["openai__types__chat__chat_completion_message_custom_tool_call_param__Custom"];
            /**
             * Type
             * @constant
             */
            type: "custom";
        };
        /**
         * ChatCompletionMessageFunctionToolCall
         * @description A call to a function tool created by the model.
         */
        ChatCompletionMessageFunctionToolCall: {
            /** Id */
            id: string;
            function: components["schemas"]["openai__types__chat__chat_completion_message_function_tool_call__Function"];
            /**
             * Type
             * @constant
             */
            type: "function";
        } & {
            [key: string]: unknown;
        };
        /**
         * ChatCompletionMessageFunctionToolCallParam
         * @description A call to a function tool created by the model.
         */
        "ChatCompletionMessageFunctionToolCallParam-Input": {
            /** Id */
            id: string;
            function: components["schemas"]["Function-Input"];
            /**
             * Type
             * @constant
             */
            type: "function";
        };
        /**
         * ChatCompletionMessageFunctionToolCallParam
         * @description A call to a function tool created by the model.
         */
        "ChatCompletionMessageFunctionToolCallParam-Output": {
            /** Id */
            id: string;
            function: components["schemas"]["openai__types__chat__chat_completion_message_function_tool_call_param__Function"];
            /**
             * Type
             * @constant
             */
            type: "function";
        };
        /** ChatCompletionRequest */
        "ChatCompletionRequest-Input": {
            /** Model */
            model: string;
            /** Messages */
            messages: (components["schemas"]["ChatCompletionDeveloperMessageParam"] | components["schemas"]["ChatCompletionSystemMessageParam"] | components["schemas"]["ChatCompletionUserMessageParam"] | components["schemas"]["ChatCompletionAssistantMessageParam-Input"] | components["schemas"]["ChatCompletionToolMessageParam"] | components["schemas"]["ChatCompletionFunctionMessageParam"])[];
            /** Max Tokens */
            max_tokens?: number | null;
            /** Tools */
            tools?: components["schemas"]["ChatCompletionFunctionTool"][] | null;
            /** Stream */
            stream?: boolean | null;
        };
        /** ChatCompletionRequest */
        "ChatCompletionRequest-Output": {
            /** Model */
            model: string;
            /** Messages */
            messages: (components["schemas"]["ChatCompletionDeveloperMessageParam"] | components["schemas"]["ChatCompletionSystemMessageParam"] | components["schemas"]["ChatCompletionUserMessageParam"] | components["schemas"]["ChatCompletionAssistantMessageParam-Output"] | components["schemas"]["ChatCompletionToolMessageParam"] | components["schemas"]["ChatCompletionFunctionMessageParam"])[];
            /** Max Tokens */
            max_tokens?: number | null;
            /** Tools */
            tools?: components["schemas"]["ChatCompletionFunctionTool"][] | null;
            /** Stream */
            stream?: boolean | null;
        };
        /**
         * ChatCompletionSystemMessageParam
         * @description Developer-provided instructions that the model should follow, regardless of
         *     messages sent by the user. With o1 models and newer, use `developer` messages
         *     for this purpose instead.
         */
        ChatCompletionSystemMessageParam: {
            /** Content */
            content: string | components["schemas"]["ChatCompletionContentPartTextParam"][];
            /**
             * Role
             * @constant
             */
            role: "system";
            /** Name */
            name?: string;
        };
        /** ChatCompletionTokenLogprob */
        ChatCompletionTokenLogprob: {
            /** Token */
            token: string;
            /** Bytes */
            bytes?: number[] | null;
            /** Logprob */
            logprob: number;
            /** Top Logprobs */
            top_logprobs: components["schemas"]["TopLogprob"][];
        } & {
            [key: string]: unknown;
        };
        /** ChatCompletionToolMessageParam */
        ChatCompletionToolMessageParam: {
            /** Content */
            content: string | components["schemas"]["ChatCompletionContentPartTextParam"][];
            /**
             * Role
             * @constant
             */
            role: "tool";
            /** Tool Call Id */
            tool_call_id: string;
        };
        /**
         * ChatCompletionUserMessageParam
         * @description Messages sent by an end user, containing prompts or additional context
         *     information.
         */
        ChatCompletionUserMessageParam: {
            /** Content */
            content: string | (components["schemas"]["ChatCompletionContentPartTextParam"] | components["schemas"]["ChatCompletionContentPartImageParam"] | components["schemas"]["ChatCompletionContentPartInputAudioParam"] | components["schemas"]["File"])[];
            /**
             * Role
             * @constant
             */
            role: "user";
            /** Name */
            name?: string;
        };
        /**
         * CheckpointInfo
         * @description Persisted checkpoint metadata exposed in the eval progress view.
         */
        CheckpointInfo: {
            /** Id */
            id: string;
            /** Ref */
            ref: string;
            /** Policy Generation */
            policy_generation: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Choice */
        Choice: {
            /**
             * Finish Reason
             * @enum {string}
             */
            finish_reason: "stop" | "length" | "tool_calls" | "content_filter" | "function_call";
            /** Index */
            index: number;
            logprobs?: components["schemas"]["ChoiceLogprobs"] | null;
            message: components["schemas"]["ChatCompletionMessage"];
        } & {
            [key: string]: unknown;
        };
        /**
         * ChoiceLogprobs
         * @description Log probability information for the choice.
         */
        ChoiceLogprobs: {
            /** Content */
            content?: components["schemas"]["ChatCompletionTokenLogprob"][] | null;
            /** Refusal */
            refusal?: components["schemas"]["ChatCompletionTokenLogprob"][] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * CompletionTokensDetails
         * @description Breakdown of tokens used in a completion.
         */
        CompletionTokensDetails: {
            /** Accepted Prediction Tokens */
            accepted_prediction_tokens?: number | null;
            /** Audio Tokens */
            audio_tokens?: number | null;
            /** Reasoning Tokens */
            reasoning_tokens?: number | null;
            /** Rejected Prediction Tokens */
            rejected_prediction_tokens?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * CompletionUsage
         * @description Usage statistics for the completion request.
         */
        CompletionUsage: {
            /** Completion Tokens */
            completion_tokens: number;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Total Tokens */
            total_tokens: number;
            completion_tokens_details?: components["schemas"]["CompletionTokensDetails"] | null;
            prompt_tokens_details?: components["schemas"]["PromptTokensDetails"] | null;
        } & {
            [key: string]: unknown;
        };
        /** CreateTunerRequest */
        CreateTunerRequest: {
            /** Name */
            name: string;
            /** Recipe */
            recipe: string | components["schemas"]["RecipeInput"];
            /** Trainer */
            trainer: string;
            /** Train Datum Ids */
            train_datum_ids: string[];
            /** Eval Datum Ids */
            eval_datum_ids?: string[];
            /** Trainer Params */
            trainer_params?: {
                [key: string]: unknown;
            } | null;
        };
        /** CreateTunerResponse */
        CreateTunerResponse: {
            /** Tuner Id */
            tuner_id: string;
            /** Name */
            name: string;
            recipe: components["schemas"]["Recipe"];
            status: components["schemas"]["TunerStatus"];
        };
        /**
         * Custom
         * @description The custom tool that the model called.
         */
        "Custom-Input": {
            /** Input */
            input: string;
            /** Name */
            name: string;
        };
        /**
         * DatumCoverage
         * @description How the datum pool is being exercised.
         */
        DatumCoverage: {
            /** In Progress */
            in_progress: number;
            /** Trained */
            trained: number;
            /** Never Trained */
            never_trained: number;
        };
        /**
         * DatumPool
         * @description Datum-pool coverage summary plus per-datum detail.
         */
        DatumPool: {
            coverage: components["schemas"]["DatumCoverage"];
            /** Items */
            items: components["schemas"]["DatumProgress"][];
        };
        /**
         * DatumProgress
         * @description Per-datum group ('Rollout') coverage, trainer view (dynamic).
         */
        DatumProgress: {
            /** Datum Id */
            datum_id: string;
            /** Next Batch Position */
            next_batch_position: number | null;
            /** Consumable */
            consumable: number;
            /** In Flight */
            in_flight: number;
            /** Expired */
            expired: number;
            /** Trained */
            trained: number;
        };
        /** DispenseRun */
        DispenseRun: {
            /** Run Id */
            run_id: string;
            /** Datum Id */
            datum_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * EvalDatumProgress
         * @description Held-out status for a single eval datum against the latest checkpoint.
         *
         *     Both counts are scoped to the newest checkpoint the eval tier is currently
         *     targeting (`EvalProgress.latest_checkpoint_generation`) -- mirroring how a
         *     training datum's `consumable` counts toward the *current* group rather than
         *     all-time -- so the numbers describe progress toward scoring that checkpoint.
         */
        EvalDatumProgress: {
            /** Datum Id */
            datum_id: string;
            /** In Flight */
            in_flight: number;
            /** Completed */
            completed: number;
        };
        /**
         * EvalProgress
         * @description Per-eval-datum held-out status rollup for a tuner.
         *
         *     `latest_checkpoint_generation` is the newest checkpoint the eval tier is
         *     currently targeting (None before any checkpoint exists); every per-datum
         *     count in `items` is scoped to it. `eval_group_size` is the target number of
         *     eval attempts per datum per checkpoint (the progress-bar denominator, from
         *     the recipe). `items` covers every registered eval datum, including ones with
         *     no runs against the latest checkpoint yet. `checkpoints` lists the persisted
         *     checkpoint records newest-first.
         */
        EvalProgress: {
            /** Latest Checkpoint Generation */
            latest_checkpoint_generation: number | null;
            /** Eval Group Size */
            eval_group_size: number;
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["EvalDatumProgress"][];
            /** Checkpoints */
            checkpoints: components["schemas"]["CheckpointInfo"][];
        };
        /**
         * File
         * @description Learn about [file inputs](https://platform.openai.com/docs/guides/text) for text generation.
         */
        File: {
            file: components["schemas"]["FileFile"];
            /**
             * Type
             * @constant
             */
            type: "file";
        };
        /** FileFile */
        FileFile: {
            /** File Data */
            file_data?: string;
            /** File Id */
            file_id?: string;
            /** Filename */
            filename?: string;
        };
        /**
         * Function
         * @description The function that the model called.
         */
        "Function-Input": {
            /** Arguments */
            arguments: string;
            /** Name */
            name: string;
        };
        /**
         * FunctionCall
         * @description Deprecated and replaced by `tool_calls`.
         *
         *     The name and arguments of a function that should be called, as generated by the model.
         */
        "FunctionCall-Input": {
            /** Arguments */
            arguments: string;
            /** Name */
            name: string;
        };
        /** FunctionDefinition */
        FunctionDefinition: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            } | null;
            /** Strict */
            strict?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * GenerationRewardStats
         * @description Reward summary for all rewarded runs at a single policy generation.
         */
        GenerationRewardStats: {
            /** Generation */
            generation: number;
            /** Count */
            count: number;
            /** Mean */
            mean: number;
            /** Std */
            std: number;
            /** Min */
            min: number;
            /** Max */
            max: number;
            /** Bins */
            bins: number[];
        };
        /** GetTunerResponse */
        GetTunerResponse: {
            /** Tuner Id */
            tuner_id: string;
            /** Name */
            name: string;
            recipe: components["schemas"]["Recipe"];
            /** Trainer */
            trainer: string;
            status: components["schemas"]["TunerStatus"];
            /** Policy Generation */
            policy_generation: number;
            /** Trainer State */
            trainer_state?: unknown | null;
            progress?: components["schemas"]["TunerProgress"];
            /**
             * Is Training
             * @default false
             */
            is_training: boolean;
            /** Last Train Op Duration Seconds */
            last_train_op_duration_seconds?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageURL */
        ImageURL: {
            /** Url */
            url: string;
            /**
             * Detail
             * @enum {string}
             */
            detail?: "auto" | "low" | "high";
        };
        /**
         * InFlightChatCompletionItem
         * @description A resumable backend chat-completion operation tracked for a tuner.
         */
        InFlightChatCompletionItem: {
            /** Run Id */
            run_id: string;
            /** Datum Id */
            datum_id: string;
            /** Request Hash */
            request_hash: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "train" | "eval";
            /** Checkpoint Generation */
            checkpoint_generation?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Run Expires At
             * Format: date-time
             */
            run_expires_at: string;
            /** Lease Expired */
            lease_expired: boolean;
            /** Recorded Completion Count */
            recorded_completion_count: number;
        };
        /** InputAudio */
        InputAudio: {
            /** Data */
            data: string;
            /**
             * Format
             * @enum {string}
             */
            format: "wav" | "mp3";
        };
        /**
         * ListDatumsResponse
         * @description The datum-id pool registered for a tuner (for filter dropdowns).
         *
         *     Scoped to a single split when the request passes `split=train`/`eval`,
         *     otherwise the full pool.
         */
        ListDatumsResponse: {
            /** Datum Ids */
            datum_ids: string[];
        };
        /** ListInFlightChatCompletionsResponse */
        ListInFlightChatCompletionsResponse: {
            /** Items */
            items: components["schemas"]["InFlightChatCompletionItem"][];
            /** Total */
            total: number;
            /** Active Lease Count */
            active_lease_count: number;
            /** Past Lease Count */
            past_lease_count: number;
            /** Oldest Created At */
            oldest_created_at?: string | null;
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ListRunsResponse */
        ListRunsResponse: {
            /** Runs */
            runs: components["schemas"]["RunItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ListTunersResponse */
        ListTunersResponse: {
            /** Tuners */
            tuners: components["schemas"]["TunerItem"][];
        };
        /**
         * Moderation
         * @description Moderation results for the request input and generated output, if moderated
         *     completions were requested.
         */
        Moderation: {
            /** Input */
            input: components["schemas"]["ModerationInputModerationResults"] | components["schemas"]["ModerationInputError"];
            /** Output */
            output: components["schemas"]["ModerationOutputModerationResults"] | components["schemas"]["ModerationOutputError"];
        } & {
            [key: string]: unknown;
        };
        /**
         * ModerationInputError
         * @description An error produced while attempting moderation.
         */
        ModerationInputError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Type
             * @constant
             */
            type: "error";
        } & {
            [key: string]: unknown;
        };
        /**
         * ModerationInputModerationResults
         * @description Successful moderation results for the request input or generated output.
         */
        ModerationInputModerationResults: {
            /** Model */
            model: string;
            /** Results */
            results: components["schemas"]["ModerationInputModerationResultsResult"][];
            /**
             * Type
             * @constant
             */
            type: "moderation_results";
        } & {
            [key: string]: unknown;
        };
        /**
         * ModerationInputModerationResultsResult
         * @description A moderation result produced for the response input or output.
         */
        ModerationInputModerationResultsResult: {
            /** Categories */
            categories: {
                [key: string]: boolean;
            };
            /** Category Applied Input Types */
            category_applied_input_types: {
                [key: string]: ("text" | "image")[];
            };
            /** Category Scores */
            category_scores: {
                [key: string]: number;
            };
            /** Flagged */
            flagged: boolean;
            /** Model */
            model: string;
            /**
             * Type
             * @constant
             */
            type: "moderation_result";
        } & {
            [key: string]: unknown;
        };
        /**
         * ModerationOutputError
         * @description An error produced while attempting moderation.
         */
        ModerationOutputError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Type
             * @constant
             */
            type: "error";
        } & {
            [key: string]: unknown;
        };
        /**
         * ModerationOutputModerationResults
         * @description Successful moderation results for the request input or generated output.
         */
        ModerationOutputModerationResults: {
            /** Model */
            model: string;
            /** Results */
            results: components["schemas"]["ModerationOutputModerationResultsResult"][];
            /**
             * Type
             * @constant
             */
            type: "moderation_results";
        } & {
            [key: string]: unknown;
        };
        /**
         * ModerationOutputModerationResultsResult
         * @description A moderation result produced for the response input or output.
         */
        ModerationOutputModerationResultsResult: {
            /** Categories */
            categories: {
                [key: string]: boolean;
            };
            /** Category Applied Input Types */
            category_applied_input_types: {
                [key: string]: ("text" | "image")[];
            };
            /** Category Scores */
            category_scores: {
                [key: string]: number;
            };
            /** Flagged */
            flagged: boolean;
            /** Model */
            model: string;
            /**
             * Type
             * @constant
             */
            type: "moderation_result";
        } & {
            [key: string]: unknown;
        };
        /**
         * NextPick
         * @description What pick_datum would dispense next, with reasoning (dynamic).
         */
        NextPick: {
            /** Datum Id */
            datum_id: string | null;
            /**
             * Tier
             * @enum {string}
             */
            tier: "incomplete" | "fresh" | "saturated" | "budget" | "none";
            /** Reason */
            reason: string;
        };
        /**
         * PromptTokensDetails
         * @description Breakdown of tokens used in the prompt.
         */
        PromptTokensDetails: {
            /** Audio Tokens */
            audio_tokens?: number | null;
            /** Cached Tokens */
            cached_tokens?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** PutRewardRequest */
        PutRewardRequest: {
            /** Reward */
            reward: number;
        };
        /** PutRewardResponse */
        PutRewardResponse: {
            /** Run Id */
            run_id: string;
            /** Reward */
            reward: number;
        };
        /**
         * Recipe
         * @description Declarative algorithm-level knobs the TunerService needs to schedule
         *     runs and form training batches. Pure data; knows nothing about backends.
         */
        Recipe: {
            /**
             * Group Size
             * @default 16
             */
            group_size: number;
            /**
             * Num Groups Per Batch
             * @default 32
             */
            num_groups_per_batch: number;
            /**
             * Max Off Policy Generation
             * @default 4
             */
            max_off_policy_generation: number;
            /**
             * Sampler Promotion Every
             * @default 4
             */
            sampler_promotion_every: number;
            /**
             * Eval Group Size
             * @default 4
             */
            eval_group_size: number;
            /**
             * Content Filter Penalty
             * @default -1
             */
            content_filter_penalty: number;
            /**
             * Length Penalty
             * @default -10
             */
            length_penalty: number;
            /**
             * Max Context Window
             * @default 60000
             */
            max_context_window: number;
        };
        /**
         * RecipeInput
         * @description Tuner-specific recipe fields layered over the Recipe defaults.
         */
        RecipeInput: {
            /** Group Size */
            group_size?: number | null;
            /** Num Groups Per Batch */
            num_groups_per_batch?: number | null;
            /** Max Off Policy Generation */
            max_off_policy_generation?: number | null;
            /** Sampler Promotion Every */
            sampler_promotion_every?: number | null;
            /** Eval Group Size */
            eval_group_size?: number | null;
            /** Content Filter Penalty */
            content_filter_penalty?: number | null;
            /** Length Penalty */
            length_penalty?: number | null;
            /** Max Context Window */
            max_context_window?: number | null;
        };
        /**
         * RewardDistributionResponse
         * @description Reward distribution bucketed by policy generation, computed server-side.
         *
         *     Replaces the former client-side aggregation over an *unbounded* run fetch:
         *     the dashboard used to download every run just to bucket rewards by
         *     generation. The server now reads only `(reward, max policy_generation)` per
         *     rewarded run -- two scalars, no JSON blobs and no full run transfer -- and
         *     returns the finished histogram. A run contributes only when it has both a
         *     reward and at least one recorded completion (so a derived generation).
         */
        RewardDistributionResponse: {
            /** Rows */
            rows: components["schemas"]["GenerationRewardStats"][];
            /** Bin Edges */
            bin_edges: number[];
            /** Bin Width */
            bin_width: number;
            /** Reward Min */
            reward_min: number;
            /** Reward Max */
            reward_max: number;
            /** Total */
            total: number;
        };
        /** RunDetailResponse */
        RunDetailResponse: {
            run: components["schemas"]["RunItem"];
            /** Completions */
            completions: components["schemas"]["ChatCompletionItem"][];
        };
        /**
         * RunItem
         * @description Summary of a single run (one attempt at a datum) under a tuner.
         */
        RunItem: {
            /** Run Id */
            run_id: string;
            /** Datum Id */
            datum_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "in_flight" | "expired" | "lost" | "length" | "content_filter" | "rewarded" | "trained" | "rejected";
            /** Reward */
            reward: number | null;
            /** Policy Generation */
            policy_generation: number | null;
            /** Trained Count */
            trained_count: number;
            /** Rejected Count */
            rejected_count: number;
            /** Completion Count */
            completion_count: number;
            /** Duration Ms Total */
            duration_ms_total?: number | null;
            /** Context Window Tokens Max */
            context_window_tokens_max?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * RunProgress
         * @description Aggregate run counts across all datums for a tuner (dynamic).
         */
        RunProgress: {
            /** Total */
            total: number;
            /** In Flight */
            in_flight: number;
            /** Expired */
            expired: number;
            /** Lost */
            lost: number;
            /** Rewarded */
            rewarded: number;
            /** Trained */
            trained: number;
            /** Rejected */
            rejected: number;
        };
        /** TopLogprob */
        TopLogprob: {
            /** Token */
            token: string;
            /** Bytes */
            bytes?: number[] | null;
            /** Logprob */
            logprob: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * TrainingProgress
         * @description Dynamic snapshot. Thresholds live on the recipe, not here.
         */
        TrainingProgress: {
            batch: components["schemas"]["BatchProgress"];
            runs: components["schemas"]["RunProgress"];
            data: components["schemas"]["DatumPool"];
            next_pick: components["schemas"]["NextPick"];
        };
        /** TunerItem */
        TunerItem: {
            /** Tuner Id */
            tuner_id: string;
            /** Name */
            name: string;
            /** Trainer */
            trainer: string;
            status: components["schemas"]["TunerStatus"];
            /** Policy Generation */
            policy_generation: number;
        };
        /**
         * TunerProgress
         * @description Optional progress snapshots attached to a tuner detail response.
         *
         *     Each field is populated only when its kind was requested via the tuner
         *     detail endpoint's `progress` query param (a comma-separated list of
         *     `train`/`eval`); un-requested kinds stay `None`.
         */
        TunerProgress: {
            train?: components["schemas"]["TrainingProgress"] | null;
            eval?: components["schemas"]["EvalProgress"] | null;
        };
        /**
         * TunerStatus
         * @description Dynamic lifecycle status of a tuner's backend training resource.
         *
         *     The value is deliberately not persisted: each trainer maps its backend's
         *     authoritative state into this small service-level lifecycle.
         * @enum {string}
         */
        TunerStatus: "PENDING" | "IN_PROGRESS" | "CANCELLED";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * FunctionCall
         * @description Deprecated and replaced by `tool_calls`.
         *
         *     The name and arguments of a function that should be called, as generated by the model.
         */
        openai__types__chat__chat_completion_assistant_message_param__FunctionCall: {
            /** Arguments */
            arguments: string;
            /** Name */
            name: string;
        };
        /**
         * FunctionCall
         * @description Deprecated and replaced by `tool_calls`.
         *
         *     The name and arguments of a function that should be called, as generated by the model.
         */
        openai__types__chat__chat_completion_message__FunctionCall: {
            /** Arguments */
            arguments: string;
            /** Name */
            name: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Custom
         * @description The custom tool that the model called.
         */
        openai__types__chat__chat_completion_message_custom_tool_call__Custom: {
            /** Input */
            input: string;
            /** Name */
            name: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Custom
         * @description The custom tool that the model called.
         */
        openai__types__chat__chat_completion_message_custom_tool_call_param__Custom: {
            /** Input */
            input: string;
            /** Name */
            name: string;
        };
        /**
         * Function
         * @description The function that the model called.
         */
        openai__types__chat__chat_completion_message_function_tool_call__Function: {
            /** Arguments */
            arguments: string;
            /** Name */
            name: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Function
         * @description The function that the model called.
         */
        openai__types__chat__chat_completion_message_function_tool_call_param__Function: {
            /** Arguments */
            arguments: string;
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_tuners_tuners_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTunersResponse"];
                };
            };
        };
    };
    create_tuner_tuners_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTunerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTunerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tuner_tuners__tuner_id__get: {
        parameters: {
            query?: {
                /** @description Comma-separated progress snapshots to attach: any of 'train' (a recipe-aware training-progress snapshot -- batch readiness, run/group coverage, next pick) and 'eval' (a per-eval-datum held-out status rollup). E.g. 'train', 'eval', or 'train,eval'. Empty (default) attaches neither. */
                progress?: string;
            };
            header?: never;
            path: {
                tuner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetTunerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_data_tuners__tuner_id__data_get: {
        parameters: {
            query?: {
                /** @description Only return datums from this split: 'train' or 'eval'. Omit to return the full pool. */
                split?: ("train" | "eval") | null;
            };
            header?: never;
            path: {
                tuner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDatumsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reward_distribution_tuners__tuner_id__reward_distribution_get: {
        parameters: {
            query?: {
                /** @description Only aggregate runs dispensed for this datum id. */
                datum_id?: string | null;
                /** @description Which runs to bucket: 'train' (rewarded training runs by completion generation) or 'eval' (held-out eval runs by the generation of the checkpoint they targeted). */
                kind?: "train" | "eval";
            };
            header?: never;
            path: {
                tuner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RewardDistributionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_in_flight_chat_completions_tuners__tuner_id__in_flight_chat_completions_get: {
        parameters: {
            query?: {
                /** @description Max operations to return per page. Omit to return all. */
                limit?: number | null;
                /** @description Opaque forward cursor from the previous workload page. */
                cursor?: string | null;
            };
            header?: never;
            path: {
                tuner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListInFlightChatCompletionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_tuners__tuner_id__runs_get: {
        parameters: {
            query?: {
                /** @description Max runs to return per page. Omit to return every run. */
                limit?: number | null;
                /** @description Opaque forward cursor from a previous response's `next_cursor`. Omit to fetch the first page. */
                cursor?: string | null;
                /** @description Only return runs dispensed for this datum id. */
                datum_id?: string | null;
                /** @description Only return runs of this kind: 'train' (runs on the training split) or 'eval' (held-out eval runs, i.e. those targeting a checkpoint). Omit to return both. */
                kind?: ("train" | "eval") | null;
            };
            header?: never;
            path: {
                tuner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRunsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dispense_run_tuners__tuner_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tuner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispenseRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_tuners__tuner_id__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tuner_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_completion_tuners__tuner_id__runs__run_id__completions__completion_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tuner_id: string;
                run_id: string;
                completion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatCompletionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_chat_completion_tuners__tuner_id__runs__run_id__openai_v1_chat_completions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tuner_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCompletionRequest-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_reward_tuners__tuner_id__runs__run_id__reward_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tuner_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutRewardRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PutRewardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
